---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: alerterator
  namespace: nais
  labels:
    app: alerterator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerterator
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        app: alerterator
    spec:
      serviceAccountName: alerterator
      containers:
      - name: alerterator
        image: {{ .image }}
        imagePullPolicy: Always
        env:
          - name: NAIS_CLUSTER_NAME
            value: {{ .env }}
