// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/nais/alerterator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Alerts returns a AlertInformer.
	Alerts() AlertInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Alerts returns a AlertInformer.
func (v *version) Alerts() AlertInformer {
	return &alertInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
