// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	alerterator_v1alpha1 "github.com/nais/alerterator/pkg/apis/alerterator/v1alpha1"
	versioned "github.com/nais/alerterator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nais/alerterator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/nais/alerterator/pkg/client/listers/alerterator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AlertInformer provides access to a shared informer and lister for
// Alerts.
type AlertInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AlertLister
}

type alertInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewAlertInformer constructs a new informer for Alert type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAlertInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAlertInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAlertInformer constructs a new informer for Alert type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAlertInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AlerteratorV1alpha1().Alerts().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AlerteratorV1alpha1().Alerts().Watch(options)
			},
		},
		&alerterator_v1alpha1.Alert{},
		resyncPeriod,
		indexers,
	)
}

func (f *alertInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAlertInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *alertInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&alerterator_v1alpha1.Alert{}, f.defaultInformer)
}

func (f *alertInformer) Lister() v1alpha1.AlertLister {
	return v1alpha1.NewAlertLister(f.Informer().GetIndexer())
}
