// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/nais/alerterator/pkg/apis/alerterator/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AlertLister helps list Alerts.
type AlertLister interface {
	// List lists all Alerts in the indexer.
	List(selector labels.Selector) (ret []*v1.Alert, err error)
	// Get retrieves the Alert from the index for a given name.
	Get(name string) (*v1.Alert, error)
	AlertListerExpansion
}

// alertLister implements the AlertLister interface.
type alertLister struct {
	indexer cache.Indexer
}

// NewAlertLister returns a new AlertLister.
func NewAlertLister(indexer cache.Indexer) AlertLister {
	return &alertLister{indexer: indexer}
}

// List lists all Alerts in the indexer.
func (s *alertLister) List(selector labels.Selector) (ret []*v1.Alert, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.Alert))
	})
	return ret, err
}

// Get retrieves the Alert from the index for a given name.
func (s *alertLister) Get(name string) (*v1.Alert, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("alert"), name)
	}
	return obj.(*v1.Alert), nil
}
